### ISSUE TITLE
\n being rendered in plain text, wrapping style 2

### ISSUE THREAD

**Issue by nickfujita** [Arnavion/libjass#103]
It appears that even when in wrapping style 2 (No word wrapping, wide lines will extend beyound the edges of the screen. Both \n and \N force line breaks.), soft line breaks (\n) are being rendered as plain text rather than as a style.

Sample file:
```
[Script Info]
ScriptType: v4.00+
Collisions: Normal
WrapStyle: 2
PlayResX: 640
PlayResY: 360

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, Strikeout, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: one,Ariel,18,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,0,0,2,0278,0226,0130,1

[Events]
Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
Dialogue: 0,0:00:00.00,0:00:03.00,one,First,0000,0000,0000,,Hello\n
Dialogue: 0,0:00:03.01,0:00:10.00,one,Second,0000,0000,0000,,Good Bye\N
```
Expected:
![image](https://user-images.githubusercontent.com/6342442/31639219-730d020a-b28c-11e7-80f2-27114f90abe2.png)

Actual:
![image](https://user-images.githubusercontent.com/6342442/31639200-5dcbd81c-b28c-11e7-9ef8-9dc4f68fad7f.png)

**Comment by Arnavion** [comment]
Yes. #91 was opened with the fix but the author closed it for some reason. Feel free to open a new PR with that fix (plus what I said in the comment).

**Comment by nickfujita** [comment]
@Arnavion PR ready for review:
https://github.com/Arnavion/libjass/pull/104
