### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by nickfujita** [Arnavion/libjass#105]
Thanks for merging in https://github.com/Arnavion/libjass/pull/104.

Would it be possible to get a new release made and uploaded to NPM? I noticed that the last one was not done since January 2016? If not, then I can make other arrangements, but just wanted to reach out to see what your release cadence is.

**Comment by Arnavion** [comment]
Unlikely that there'll be a new release. Most of the functional tests were broken last time I checked, and I don't plan on updating them.

Just use master.

**Comment by nickfujita** [comment]
@Arnavion Thanks for confirming :)
