### ISSUE TITLE
When playing preroll ads, sometimes the text appears very small

### ISSUE THREAD

**Issue by DoomTay** [Arnavion/libjass#108]
[Sample set](https://github.com/SunnyLi/videojs-ass/files/2052491/heisenbug.zip)

This happens with a simple implementation of videojs-contrib-ads (heisenbug.html) and with videojs-vast-vpaid (heisenbug2.html), though the latter case is much, much rarer.

I noticed that when this happens, the style of span elements for subtitle lines are missing the font attribute. It seems that something about how both plugins set up ad playback interferes with span styling somehow, even though only one of them makes use of videojs-contrib-ads/

I'm not sure how to trace this further, but because it involves span styling, it seems this is a libjass issue.

**Comment by Arnavion** [comment]
As [the documentation](https://arnavion.github.io/libjass/api.xhtml#libjass.renderers.WebRenderer) says

>After the renderer fires its ready event, [libjass.renderers.WebRenderer.resize](https://arnavion.github.io/libjass/api.xhtml#libjass.renderers.WebRenderer.resize) must be called to initialize its size before starting the clock.

However videojs is starting the clock before calling `resize`, thus `WebRenderer.preRender` is getting called while its `scaleX` and `scaleY` properties have not been uninitialized. videojs needs to fix this.
