### ISSUE TITLE
[Feature Request]Can you convert a .ass subtitle to VobSub format?

### ISSUE THREAD

**Issue by KingMario** [Arnavion/libjass#114]
Great Job!

Can you convert a .ass subtitle to VobSub format? Like HTML to Canvas to JPG/PNG and then to SubVob?

This would be very convenient to package a video with a VobSub subtitle if the .ass subtitle includes lines with special fonts may not be available in the viewer's computer.

Thanks.

**Comment by Arnavion** [comment]
>Can you convert a .ass subtitle to VobSub format? Like HTML to Canvas to JPG/PNG and then to SubVob?

This sounds like it should be done with the program of your choice, rather than with javascript inside a browser running on your server.

>if the .ass subtitle includes lines with special fonts may not be available in the viewer's computer.

This by itself shouldn't be a reason to not use .ass, since your user's browser probably supports web fonts.

**Comment by KingMario** [comment]
Good points.

Actually, I'm looking for a local tool as a converter. Then I can package the VobSub subtitle to the video as a .mkv file. I've done lots of searches, but have found no handy tool to do it. I've only found a Son2VobSub tool is related.
During the way searching, I see many guys have the same requirement to save the existing fonts in subtitles.

If distributed online, using web fonts is a good solution. But if the font files are large (e.g. Chinese fonts), the page would be loaded very slowly. If a .ass file is converted to VobSub format, it may possibly reduce the size.

Thanks a lot for your reply. I think I should do more googling on a .ass to .son converter. The tools about this format seem rare.
