### ISSUE TITLE
when I create new dialogue can I get a dialogue class tag?

### ISSUE THREAD

**Issue by jokerrider007** [Arnavion/libjass#116]
relate from: [https://github.com/Arnavion/libjass/issues/106](https://github.com/Arnavion/libjass/issues/106)

I store my ASS object in the server and send ASS object to the client then I'm trying to add some new dialogue from the client and push dialog back to the server.

<pre>
let dialog = new window.libjass.Dialogue(new Map([
          ['Style', 'Default'],
          ['Start', 1],
          ['End', 5],
          ['Text', 'Text']
        ]), ass)
</pre>

when I push a `dialog` into ASS object collection. my new dialogue doesn't have a class tag.
Now I'm hard-code to add a class tag into dialog before push it into ASS object.
what is the best way can I get a dialogue class tag or add new dialogue into server side?

**Comment by Arnavion** [comment]
>my new dialogue doesn't have a class tag.

Yes it does. If you do `console.log(dialog._classTag);` you will see it.
