### ISSUE TITLE
Support `catch` in `Promise` shim

### ISSUE THREAD

**Issue by rcombs** [Arnavion/libjass#23]
For compatibility with the official API (and browsers' native implementations). I _think_ this should be a couple extra prototypes in the interface section and a 1-line wrapper function.

**Comment by Arnavion** [comment]
This was fixed by https://github.com/Arnavion/libjass/commit/71151b2

>Make sure you do this before using any libjass API that returns you a promise, since I do not guarantee that an instance of SimplePromise works with instances of any other type of Promise.

Since SimplePromise follows the Promises/A+ spec correctly, it should in fact work with instances of other types of Promise.

The recommendation to use a more featured and performant library still stands.
