### ISSUE TITLE
Better Example

### ISSUE THREAD

**Issue by maxx1985** [Arnavion/libjass#33]
Hi, i'm relatively new to Javascript, i've seen the ''online demo'', it works fine, but the script is too complex to understand and edit, is it possible a simple ''hello world script''?
Something like:
-script-
  var video = VIDEO_URL
  var sub = ASS_URL
  //SOME CODE TO RUN LIBJASS on idvideo
-/script-
-video id='idvideo'- -/video-

Thanks for attention

**Comment by Anime4000** [comment]
You can take a look on my example:
https://kwikmandarin.net/content/demo/html5-ass/index3.html

simply see Source Script :+1:

**Comment by Arnavion** [comment]
Yes, it could do with some more comments. Meanwhile:

1. Use the ASS URL to fetch the ASS object.

    ```javascript
    var assLoadedPromise = libjass.ASS.fromUrl(assUrl);
    ```

    Note that this is a Promise, i.e., an async operation.

1. Get a reference to the video element.

    ```javascript
    var video = document.querySelector("#idvideo");
    ```

1. Use DefaultRenderer to render subs.

    ```javascript
    assLoadedPromise.then(function (ass) {
        var renderer = new libjass.renderers.DefaultRenderer(video, ass);
    });
    ```

**Comment by maxx1985** [comment]
It works!!! Nice! Thanks a lot for the exaustive explanation!

the code that worked for me is the ''basic one''
```html
<video id="player" controls='controls' >
	<source src="VIDEO_URL_HERE" type="video/mp4">
```
```javascript
	<script>
		var assLoadedPromise = libjass.ASS.fromUrl("ASS_URL_HERE");
		var video = document.querySelector("#player");
		assLoadedPromise.then(function (ass) {
			var renderer = new libjass.renderers.DefaultRenderer(video, ass);
		});
	</script>
```
```html
</video>
```

Thanks also to Anime4000 i've used the basic structure of your work

**Comment by Arnavion** [comment]
http://arnavion.github.io/libjass/demo/index.js now contains more comments. I hope that helps.
