### ISSUE TITLE
Letter spacing thrown off by a mix of italic and regular types

### ISSUE THREAD

**Issue by ericmatthys** [Arnavion/libjass#58]
The problem arises when there is a line with both italic and regular types.

`254 00:27:00,560 --> 00:27:04,997 Im <i>Hollywood Bowl</i> hatten zwar bereits die Beatles gespielt, `

With libjass:

![screen shot 2015-11-12 at 3 57 55 pm](https://cloud.githubusercontent.com/assets/1154586/11133904/2b8279b2-8956-11e5-8abd-3fe7dc0047d3.png)

Without libjass:

![screen shot 2015-11-12 at 3 58 28 pm](https://cloud.githubusercontent.com/assets/1154586/11133913/3c916bf0-8956-11e5-877a-0314f1de64c4.png)

**Comment by Arnavion** [comment]
Try https://github.com/Arnavion/libjass/compare/fix-58

I'll see if there's a less hacky way of doing it before merging it.

**Comment by ericmatthys** [comment]
Sorry for the very late response. Here's a comparison between 0.10 an 0.11.

**0.10**
![screen shot 2016-04-06 at 12 08 14 pm](https://cloud.githubusercontent.com/assets/1154586/14327618/56f869f0-fbf0-11e5-876f-0362596c17cb.png)

**0.11**
![screen shot 2016-04-06 at 12 04 00 pm](https://cloud.githubusercontent.com/assets/1154586/14327616/54b299cc-fbf0-11e5-87c1-a11ffab56dc8.png)

**Comment by Arnavion** [comment]
Your original example:

![image](https://cloud.githubusercontent.com/assets/1096010/14327907/49d2bffc-fbe9-11e5-9d88-6d0121728cfa.png)

Assuming your new one is `Did you <i>hear</i> that?` :

![image](https://cloud.githubusercontent.com/assets/1096010/14327943/7102e1c4-fbe9-11e5-8452-5438ff26a5a2.png)

**Comment by Arnavion** [comment]
(Test it on https://arnavion.github.io/libjass/demo/ and see what you get.)
