### ISSUE TITLE
Outline color looks pale

### ISSUE THREAD

**Issue by soruly** [Arnavion/libjass#61]
The original image
![ori](https://cloud.githubusercontent.com/assets/1979746/12217893/a9906c62-b749-11e5-8266-0b3cdef292bd.png)

The subtitle displayed
![2](https://cloud.githubusercontent.com/assets/1979746/12217894/ae6cce2e-b749-11e5-9df2-e0bc9649523e.png)

The subtitle file
```
[Script Info]
Title: プラスティック・メモリーズ #01 予告
Original Script: FLsnow
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes
ScriptType: v4.00+

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,SimHei,46,&H00FBFBFB,&H000000FF,&H00B89144,&H96000000,0,0,0,0,100,100,1,0,1,1.66667,1,2,15,15,20,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.26,0:00:04.44,Default,,0,0,0,,大家好 我是終末服務課的絹島美智瑠
```

**Comment by soruly** [comment]
Referring to this issue https://github.com/awgreenblatt/gradientmaps/issues/1
It looks like it's something related to color-interpolation-filters on feComponentTransfer
A quick fix would be like:
```
var coloredSource = document.createElementNS("http://www.w3.org/2000/svg", "feComponentTransfer");
coloredSource.setAttribute("color-interpolation-filters","sRGB");
filterElement.appendChild(coloredSource);
```
The result:
![3](https://cloud.githubusercontent.com/assets/1979746/12217964/8bf467ec-b74b-11e5-9dbb-d15378c6882a.png)

**Comment by Arnavion** [comment]
Ah, that link confused me initially, but I understand it now. It's not that Chrome is doing the wrong thing by defaulting to linearRGB. There are *two* properties `color-interpolation` and `color-interpolation-filters`, where the former defaults to sRGB and the latter to linearRGB.
