### ISSUE TITLE
Letterboxing calculation is wrong

### ISSUE THREAD

**Issue by Arnavion** [Arnavion/libjass#62]
Currently WebRenderer assumes letterboxing is a function of the target resolution and script resolution. This is wrong - for example if video is 1280x720 (1.78:1), script is 720x480 (1.5:1), and WebRenderer is told to resize to 1280x720, it assumes letterboxing on the sides and resizes the subs wrapper to  1080x720 (1.5:1).

Instead, letterboxing is a function of the target resolution and *video* resolution. So in the above case WebRenderer should resize the subs wrapper to 1280x720.

Suppose a case where target resolution is 1280x800. *Now* WebRenderer should assume letterboxing on the top and bottom and resize the subs wrapper to 1280x720, with 40px dead space above and below.

Since WebRenderer does not know about the actual video resolution (or anything about the video at all), it cannot do letterboxing. Instead, the caller of WebRenderer.resize must calculate the letterboxing themselves using a similar calculation as WebRenderer does now.

DefaultRenderer can do it since it knows the video resolution.

**Comment by Arnavion** [comment]
@SunnyLi This will be a breaking change for videojs-ass since it uses WebRenderer. You'll have to do the same calculation as DefaultRenderer does now - https://github.com/Arnavion/libjass/blob/9b0e15c/src/renderers/default.ts#L50-L61 - and change your call to WebRenderer.resize

**Comment by SunnyLi** [comment]
@Arnavion Thanks. I'll keep this in mind when upgrading to the next version of libjass.
