### ISSUE TITLE
odd problem with subtitle border in Google chrome

### ISSUE THREAD

**Issue by ken-lofi** [Arnavion/libjass#63]
hello
first. i'am using v0.10
here my problem in google chrome
![sans titre](https://cloud.githubusercontent.com/assets/14111009/12532477/6812b2b4-c215-11e5-85a9-4d5e653926e8.png)

but in mozilla like this
![sans titre1](https://cloud.githubusercontent.com/assets/14111009/12532485/c743009a-c215-11e5-9b2e-858b4eae77a6.png)

+++++
another problem
browser can't load from device the fonts which have oblique police style like this
![sans titre2](https://cloud.githubusercontent.com/assets/14111009/12532522/64a80bc8-c216-11e5-9db0-530cbdc26bdc.png)

but load so easy normal font
![sans titre3](https://cloud.githubusercontent.com/assets/14111009/12532527/7b6cad46-c216-11e5-9bcc-92b8f9840a95.png)

++++
font size always existe

**Comment by Arnavion** [comment]
The first one is probably Chrome bug https://code.google.com/p/chromium/issues/detail?id=554169 Which version of Chrome are you using? You can work around it by disabling use of SVG filters by setting [enableSvg property in renderer settings](http://arnavion.github.io/libjass/api.xhtml#libjass.renderers.RendererSettings.enableSvg) to false.

For the second one, in your `@font-face` rule make sure you have `font-style: oblique;`

**Comment by ken-lofi** [comment]
i'am using v 47.0.2526.111 of google chrome
i don't understand how to disable SVG!!!
*****

ABOUT @font-face,, which one exactly... in my website or the browser??

**Comment by ken-lofi** [comment]
libjass v0.11
when will be released?

**Comment by ken-lofi** [comment]
??

**Comment by soruly** [comment]
@ken-lofi you can disable svg like this
```javascript
var rendererSettings = new libjass.renderers.RendererSettings();
rendererSettings.enableSvg = false;
```
Then pass the rendererSettings object into your renderer
```javascript
renderer = new libjass.renderers.WebRenderer(ass, clock, overlay, rendererSettings);
```

**Comment by Arnavion** [comment]
By the way, doing `new libjass.renderers.RendererSettings()` is not necessary. All the renderers accept an object literal for the settings parameter like `{ enableSvg: false, }` and [internally convert it to a  RendererSettings](https://github.com/Arnavion/libjass/blob/509aa3b/src/renderers/null.ts#L47) with [RendererSettings.from()](https://github.com/Arnavion/libjass/blob/509aa3b/src/renderers/settings.ts#L150-L156)

I've only kept RenderSettings as a public class for backward-compatibility, and will probably make it private in 1.0
