### ISSUE TITLE
Weird characters â€Œ being rendered in dialogs

### ISSUE THREAD

**Issue by atomjack** [Arnavion/libjass#65]
I'm displaying subtitles (on a Chromecast) from a stream, using minimalASS:

```
var xhr = new XMLHttpRequest();
var stream = new libjass.parser.XhrStream(xhr);
var streamParser = new libjass.parser.StreamParser(stream);
streamParser.minimalASS.then(function (ass) {
    var renderer = new libjass.renderers.DefaultRenderer(video, ass);
    renderer.addEventListener('ready', function() {
        video.play();
    });
}).catch(function(error) {});
xhr.open('GET', url, true);
xhr.send();
```

I had to do it this way as the Promise would never resolve when I used fromUrl, I'm guessing since it is a stream that doesn't complete loading.

The dialogs are showing up, however every dialog has some weird characters included, specifically `â€Œ`, where every newline in the dialog is. The original subtitle line does not contain these characters, as both viewing the stream in my browser and using debugMode, the characters aren't there (but they are being displayed when rendered).

Here's an example of a dialog line from the stream:
`Dialogue: 0,0:29:15.92,0:29:21.72,Default,,0,0,0,,First line.\NSecond line.`

But it renders as:
```
First line.â€Œ
Second line.â€Œ
```

I'm guessing it's an encoding issue, but I haven't been able to figure out how to solve it. I've tried specifying the encoding in the xhr request, using e.g. `xhr.overrideMimeType('text/vtt; charset=utf-8');` (I also tried iso-8859-1), as well as `xhr.setRequestHeader('Content-type', 'text/vtt; charset=utf-8')` (between xhr.open() and xhr.send()) but to no avail.

**Comment by Arnavion** [comment]
It's not the subs, it's libjass.js. Your browser is not interpreting libjass.js as utf-8. The mojibake is coming from the \u200C that libjass [adds at the end of every text part.](https://github.com/Arnavion/libjass/blob/509aa3/src/renderers/web/renderer.ts#L786) It's converted to the actual unicode character by the TS compiler which your browser is misinterpreting as local system encoding.

**Comment by atomjack** [comment]
Ahhh interesting. My compiled .js file had the resulting line as 
`currentSpan.appendChild(document.createTextNode(part.value + ""));` in my IDE, although in vi it shows up as a special character: <200c>.

I removed the `+ ""` and the weird characters went away. I even tried replacing it with ` + "\u200C"` and that looks fine as well. 

I'm not sure what else the fix should be, so I can close this if you want. Thanks!

**Comment by Arnavion** [comment]
Yes, like I said >It's converted to the actual unicode character by the TS compiler (`0xe2 0x80 0x8c`)

You shouldn't remove it since it was added to fix #58 Like I said, the fix needs to be on your end to add charset header or add BOM to libjass.js, whichever one is easier for you.

**Comment by Arnavion** [comment]
Okay, it's actually UJS that does this, not TS.

To be honest, I think I'll just change it to emit the original Unicode escape. I don't see the point of replacing it with the actual character.

**Comment by atomjack** [comment]
Thanks! That did the trick!
