### ISSUE TITLE
Critical Problem, please help me ASAP

### ISSUE THREAD

**Issue by giggioman00** [Arnavion/libjass#66]
Weeks ago I tested libjass on videojs-ass.
In localhost everything worked fine.
The problem is that now, in the production site, subtitles doesn't appear. This seems strange, because localhost and production site have the same code.
Anyway, now doesn't work. 
Is there any php software/extension that I should install for let the plugin works? I don't know, maybe php-xml or something like that?

EDIT: On console I get this error: fetch() failed, falling back to XHR:  Error: Not supported.

**Comment by Arnavion** [comment]
https://github.com/Arnavion/libjass/issues/64#issuecomment-176316325

**Comment by Arnavion** [comment]
```irc
<giggioman00> as I said on github, appear this error on console: fetch() failed, falling back to XHR: Error: Not supported.
```

It is not an error. [I've suppressed it to avoid confusion.](https://github.com/Arnavion/libjass/commit/1de86c4)

```irc
<giggioman00> anyway, I don't know why but now everything seems to work fine for me
```

Good.


```irc
<giggioman00> but I get two comments under that video
<giggioman00> one comment say that he can't see subtitles
<giggioman00> the other comments say that on mobile phone he cannot see the subtitle, while on PC Desktop the subtitle are out of synch
<giggioman00> Anyway, I don't know more about their OS, browser and so on... 
<giggioman00> And I don't think they will answer if I ask them this
```
Then when you have that info you can reopen this bug.

**Comment by giggioman00** [comment]
Ok, I get an answer from the guy of second comment.
He use a laptop as PC Desktop, O.S. is android and he use google chrome as browser. He also said to have used firefox and opera but faced the same problem.
On mobile, he have a windows phone with google chrome

**Comment by Arnavion** [comment]
Chrome on Android lag issue is https://code.google.com/p/chromium/issues/detail?id=509010
