### ISSUE TITLE
About font metric while preloading

### ISSUE THREAD

**Issue by ken-lofi** [Arnavion/libjass#67]
hello aranv... hope that u^^ fine
i want o know if this version https://raw.githubusercontent.com/Arnavion/libjass/gh-pages/demo/libjass.js
contain font metric https://github.com/Arnavion/libjass/commit/c6cafd10d43d56968f2010bb1c6e3291908f9ae3

++
and when will u release the last version cauze i have a website and i want to use the last version 
and thanks

**Comment by Arnavion** [comment]
![image](https://cloud.githubusercontent.com/assets/1096010/13063869/85703554-d401-11e5-87c1-984605f55468.png)

![image](https://cloud.githubusercontent.com/assets/1096010/13063879/af251e00-d401-11e5-8c87-113b1b3e49e2.png)
