### ISSUE TITLE
[demo] Ask user if their browser supports SVG filter effects, and set enableSvg accordingly

### ISSUE THREAD

**Issue by Arnavion** [Arnavion/libjass#71]
Eg: Write some text in black and color it red with an SVG filter. Ask user if the text is red or black.

**Comment by XCanG** [comment]
@Arnavion you mean something like this? http://pastebin.com/PwBmitCG
If yes, worked both in Firefox, Chrome, Edge _(Windows 10 IE)_

**Comment by Arnavion** [comment]
No. That applies SVG filters on SVG text, which is a different feature from SVG filters on HTML that libjass uses. But similar, yes.

**Comment by Arnavion** [comment]
And FYI, [Edge doesn't support it yet either.](https://connect.microsoft.com/IE/feedback/details/2379118)
