### ISSUE TITLE
Line height is incorrect in rotated text. Also \p1 is not renderred.

### ISSUE THREAD

**Issue by pushrbx** [Arnavion/libjass#75]
The ass code on Layer 1:
`{\an4\frz270\c&HF8F3F4&\3c&H585453&\alpha&H44&\bord1\blur0.333\fs21\b1\fscx90\fscy100\pos(701,130)}Satou felfedte a tervezett\Nbűntetteit az interneten, `
Ass code on Layer 0:
`{\p1\c&HDBD8D8&\1a&H6B&\fscx102\fscy100\blur0.333\frz89.85\pos(700,221)}m 0 0 l 195 0 l 195 60 l 0 60 l 0 0, `
Both of them are at the same frame number. (Start = 0:00:36.05 in the attached ass file.)

It looks like this: [Image1](https://archiverbx.blob.core.windows.net/gifs/rotated_text_doesnt_render_properly.png)

And it should look like this: [Image2](https://archiverbx.blob.core.windows.net/gifs/rotated_text_doesnt_render_properly2.png)

I've shot the second image while using [ass.js.org](https://ass.js.org/) ([Github](https://github.com/weizhenye/ASS))

I know that \an4 is a known issue, but the rectangle should be there somehow.

I'm using:
Firefox 46, Windows 10
Video: [Ajin - 09.mp4](http://bit.ly/1SwQK2H)
Ass: [Link](https://archiverbx.blob.core.windows.net/gifs/%5BOhys-Raws%5D%20Ajin%20-%2009%20(TBS%201280x720%20x264%20AAC).ass)

**Comment by Arnavion** [comment]
(\an4 is not supposed to be broken for for absolutely-positioned subs. Since your lines have \pos they're supposed to work.)

**Comment by Arnavion** [comment]
The bug for the two text lines is that the transform-origin on the two lines is set to `50% 50%`. It should be set to `0% 50%`

**Comment by pushrbx** [comment]
I've just tested it again and it doesn't even show it now and it stops displaying the subsequent dialogues. I was using the [demo site](http://arnavion.github.io/libjass/demo/index.xhtml).

**Comment by pushrbx** [comment]
I've tested it again. Around that area in time where this transformed text takes place it stops displaying any other dialogues, also it doesn't show the background. I think it's because of the layers. Same video, same ass file. I was using the demo site.

**Comment by Arnavion** [comment]
Yes, something broken with FF. Chrome is fine.

**Comment by Arnavion** [comment]
Will fix in #77
