### ISSUE TITLE
name.toLowerCase is not a function

### ISSUE THREAD

**Issue by Statfine** [Arnavion/libjass#86]
when i import libjass.js from v0.11.0, it show "Module build failed: TypeError: /.../libjass.js: name.toLowerCase is not a function"; but i do not found toLowerCase in libjass.

**Comment by Yay295** [comment]
`toLowerCase` is a function available to strings by default in JavaScript. I'd guess that in this case `name` is not a string, though it is expected to be.

**Comment by Arnavion** [comment]
>Module build failed:

The error is from whatever module loader or bundler you're using, not libjass.
