### ISSUE TITLE
If I update the page does not work.

### ISSUE THREAD

**Issue by dariomadeira** [Arnavion/libjass#93]
I have a problem with libjass, when I load my page for the first time it shows the subtitles without problem, if I reload all web page the subtitles are not shown, but if I delete the browser cache and load the page again the subtitles are perfectly displayed.

http://gdurl.com/61GU

What to do ?:

`video{
	margin: 0 auto; 
	padding: 0;
}
body{
	background-color:black;
}`

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>test 5</title>
	<script src="js/jquery.js" type="text/javascript"></script>
  <script src="js/libjass.js" type="text/javascript"></script>
  <link href="css/libjass.css" rel="stylesheet">
  <link href="css/style.css" rel="stylesheet">
</head>
<body>
  <video poster="" id="myvideo">
    <source src="video.mp4" type="video/mp4">
  </video>
  <script>
    $(document).ready(function() {
      var assLoadedPromise = libjass.ASS.fromUrl("https://myadresstoass/video.ass");
        var video = document.querySelector("#myvideo");
      assLoadedPromise.then(function (ass) {
        var renderer = new libjass.renderers.DefaultRenderer(video, ass);
        renderer.addEventListener("ready", function () {
          video.play();
        });
        // resize
        var w =  ($(window).width()) -20;
        var h = ($(window).height()) -30;
        $("#myvideo").height(h);
        $("#myvideo").width(w);        
        renderer.resize(w, h);
        $(window).resize(function() {
          var w =  ($(window).width()) -20;
          var h = ($(window).height()) -30;
          $("#myvideo").height(h);
          $("#myvideo").width(w);
          renderer.resize(w, h);
        });
      });
    });
  </script>
</body>
</html>
```

**Comment by Yay295** [comment]
> if I update the page

What do you mean by "update"?

Also, please put your code in a `code block`. Just select it all and hit that button that looks like `<>`.

**Comment by dariomadeira** [comment]
Apologies for my english!.... is reload all web page.... load page again

**Comment by Arnavion** [comment]
I cannot reproduce.

Does it happen to you in just Chrome or every browser? If just Chrome, what version?

Share a link to your web page so I can see.

**Comment by dariomadeira** [comment]
Hi, thanks for your help! this project I have in my PC, I have uploaded a functional example in:

https://drive.google.com/file/d/0B6MbnYNUNWmBb3h6S1pTbmt5Vjg/view?usp=sharing

My version of chrome is Version 59.0.3071.109 (Official build) (64 bits) and in firefox does not occur the error.

Sorry for the example, is what I found faster.

Look at the pictures:

http://gdurl.com/puk9

Thanks!!

**Comment by dariomadeira** [comment]
I have an idea of what happens:
The first time, wait for the ASS download into the cache.

`var assLoadedPromise = libjass.ASS.fromUrl("https://myadresstoass/video.ass");`

When downloading:

```
var video = document.querySelector("#myvideo");
      assLoadedPromise.then(function (ass) {
        var renderer = new libjass.renderers.DefaultRenderer(video, ass);
        renderer.addEventListener("ready", function () {
          video.play();
        });
```

The second time does not wait to download ASS file to cache, play video while downloading the ASS file...
When finish downloading it shows on screen, with fast connections is almost imperceptible.

I need another method to determine when assLoadedPromise has downloaded the ASS into cache.

**Comment by Arnavion** [comment]
Nothing to do with that. It's because after soft reload the DefaultRenderer's div does not have dimensions set on it for some reason.

**Comment by Arnavion** [comment]
Okay, it's because `video.videoWidth` is 0 when you call `renderer.resize(w, h)` so the scaling hits Infinity and NaN and blows up.

Move your `renderer.resize` call till after the video is loaded.

**Comment by Arnavion** [comment]
Note that this is the same reason why the demo page waits for ASS *and* video metadata to be loaded before creating the renderer - https://github.com/Arnavion/libjass/blob/b1317311/demo/index.js#L351-L361

**Comment by dariomadeira** [comment]
I'm sorry but I do not understand what's wrong, I mentioned earlier that it's the worst example I've seen because it's not simple and it's very complex.
For me a good example is a video, an ass and that runs all without resize problem.
When I said that they gave me the example: https://github.com/Arnavion/libjass/issues/33#issuecomment-72072597
Based on that example I made my code.
I do not understand what is wrong and how I can move renderer.resize call till after the video is loaded.
But why in Firefox works perfectly?

You can help? Thank you!

**Comment by Yay295** [comment]
This should work:

```<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>test5</title>
  <script src="js/jquery.js" type="text/javascript"></script>
  <script src="js/libjass.js" type="text/javascript"></script>
  <link href="css/libjass.css" rel="stylesheet">
  <link href="css/style.css" rel="stylesheet">
</head>
<body>
  <video poster="" id="myvideo">
  <source src="otro.mp4" type="video/mp4">
  </video>
  <script>
    $(document).ready(function() {
      var video = document.getElementById("myvideo");
      var assLoadedPromise = libjass.ASS.fromUrl("https://sunnyli.github.io/videojs-ass/subs/OuterScienceSubs.ass");
      assLoadedPromise.then(function (ass) {
        function resizeSubs() {
          // calcular el tamaño aca
          var w =  ($(window).width()) -20;
          var h = ($(window).height()) -30;
          $("#myvideo").height(h);
          $("#myvideo").width(w);
          renderer.resize(w,h);
        }

        var renderer = new libjass.renderers.DefaultRenderer(video, ass);
        renderer.addEventListener("ready", function() {
          if (video.readyState) {
            resizeSubs();
            video.play();
          } else {
            video.addEventListener("loadedmetadata", function() {
              resizeSubs();
              video.play();
            });
          }
        });

        $(window).resize(resizeSubs);
      });
    });
  </script>
</body>
</html>```
