### ISSUE TITLE
Cannot read property 'fontMap' of undefined

### ISSUE THREAD

**Issue by kozec** [Arnavion/libjass#94]
It appears that .settings property of WebRenderer is not being set anywhere, at least not before its first use at https://github.com/Arnavion/libjass/blob/master/src/renderers/web/renderer.ts#L150

My backtrace:
libjass.js:5904 Uncaught (in promise) TypeError: Cannot read property 'fontMap' of undefined
    at Object.WebRenderer (libjass.js:5904)
    at Object.DefaultRenderer (libjass.js:5176)
    at VideoPlayer.subtitles_parsed (index.py.js:2928)
    at index.py.js:38
    at <anonymous>

**Comment by Arnavion** [comment]
https://github.com/Arnavion/libjass/blob/master/src/renderers/web/renderer.ts#L118
https://github.com/Arnavion/libjass/blob/master/src/renderers/null.ts#L47

**Comment by aahmyu** [comment]
<img width="431" alt="image" src="https://user-images.githubusercontent.com/5700557/46569633-1f0c3980-c958-11e8-914f-b7c964e6c664.png">

Trying to implement this in an angular component and can't get it to work for the life of me :(

**Comment by Arnavion** [comment]
`this.render = libjass.renderers.DefaultRenderer(...)` is missing a `new`
